learning_log/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shows.urls',namespace ='shows')),
] 
 
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shows/urls.py
from django.urls import path
from . import views

app_name = 'shows'

urlpatterns = [
    path('',views.allshows, name='allshows'),
    path('new_page',views.new_page, name='new_page'),
    path('show_detail/(?P<show_id>\+d)',views.show_detail, name='show_detail'),
    path('edit_show/(?P<show_id>\+d)',views.update_show, name='edit_show'),
    path('delete_show/(?P<delete_id>\+d)',views.delete_show, name='delete_show'),
    path('search_show',views.search_show, name='search_show')
]

shows/models.py
from django.db import models

# Create your models here.
class Show(models.Model):
    title = models.CharField(max_length=200)
    network = models.CharField(max_length = 50)
    released_date = models.DateField()
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True, blank=True,null=True)
    updated = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='images/', blank=True)
    
    def __str__(self):
        return self.title

shows/forms.py
from django import forms
from .models import Show

class ShowForm(forms.ModelForm):
    class Meta:
        model = Show
        fields = '__all__'
        initial = '__all__'
        description = {'text': forms.Textarea(attrs={"rows":10, "cols":20})}
 

shows/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import Paginator
from .models import Show
from .forms import ShowForm
# Create your views here.
def allshows(request):
    shows = Show.objects.all()
    paginator = Paginator(shows,5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'shows' : shows,
        'page_obj': page_obj
    }
    return render(request, 'shows/allshows.html',context)

def new_page(request):
    if request.method == 'POST':
        form = ShowForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('shows:allshows'))
    else:
        form = ShowForm()
    context ={'form': form}
    return render(request,'shows/new_page.html',context)

def show_detail(request,show_id):
    this_show = Show.objects.get(id=show_id)
    context = { 'this_show': this_show }
    return render(request,'shows/show_detail.html', context)

def update_show(request,show_id):
    update_show = Show.objects.get(id=show_id)
    if request.method != 'POST':
        print("It's not a post request")
        form = ShowForm(instance=update_show)
    else:
        form=ShowForm(instance=update_show,data=request.POST,files=request.FILES)
        print('It is a post request')
        if form.is_valid():
            form.save()
            print('form saved')
            return HttpResponseRedirect(reverse('shows:show_detail', args=[update_show.id]))
    context = {'update_show': update_show, 'form':form}
    return render(request,'shows/update_show.html',context)

def delete_show(request,delete_id):
    delete_this = Show.objects.get(id=delete_id)
    delete_this.delete()
    return redirect('shows:allshows')

def search_show(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        searched_show = Show.objects.filter(title__contains=searched)
        # paginator = Paginator(searched_show,2)
        # page_number = request.POST.get('page')
        # page_obj = paginator.get_page(page_number)
        context = {
            'searched': searched, 
            'searched_show':searched_show, 
            # 'page_obj':page_obj
        }
        return render(request,'shows/search_show.html', context)
    else:
        print('get a get request')
        return redirect(request,'shows/allshows.hmtl')

shows/templates/shows/allshows.html
{% extends 'shows/base.html' %}
{% load static %}
{% block content %}
    <table class="table align-middle text-center">
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Title</th>
            <th scope="col">Network</th>
            <th scope="col"><a href="{% url 'shows:allshows' %}?sort=released_date">Release Date</</th>
            <th scope="col">Action</th>
        </tr> 
        {% for show in page_obj %}
        <tr>
            <td><a href="{% url 'shows:show_detail' show.id %}">{{ show.id }}</a></td>
            <td>{{ show.title }}</td>
            <td>{{ show.network }}</td>
            <td>{{ show.released_date }}</td>
            <td>
                <a class='btn btn-primary' href="{% url 'shows:show_detail' show.id %}">Show</a>
                <a class='btn btn-secondary' href="{% url 'shows:edit_show' show.id %}">Edit</a>
                <a class='btn btn-danger' href="{% url 'shows:delete_show' show.id%}">Delete</a>
            </td>
        </tr>
        {% endfor %}
    </table>
    <br>
    <nav aria-label="...">
        <ul class="pagination pagination justify-content-center">
            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">Top</a>
                            <a href="?page={{ page_obj.previous_page_number }}">
                                <i class="fas fa-hand-point-left"></i>
                            </a>
                    {% endif %}
                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                    </span>
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">
                            <i class="fas fa-hand-point-right"></i>
                        </a>
                        <a href="?page={{page_obj.paginator.num_pages }}">Bottom</a>
                    {% endif %}
                </span>
            </div>
        </ul>
    </nav>
 
{% endblock content %}

shows/templates/shows/base.html
{% load static %}
<!-- Font Awesome -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
  rel="stylesheet"
/>
<!-- Google Fonts -->
<link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
  rel="stylesheet"
/>
<!-- MDB -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.3.0/mdb.min.css"
  rel="stylesheet"
/>
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <!-- Container wrapper -->
        <div class="container-fluid">
          <!-- Navbar brand -->
          <i class="fas fa-film"></i>
      
          <!-- Toggle button -->
          <button
            class="navbar-toggler"
            type="button"
            data-mdb-toggle="collapse"
            data-mdb-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <i class="fas fa-bars"></i>
          </button>
      
          <!-- Collapsible wrapper -->
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left links -->
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <!-- <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li> -->
                <li class="nav-item">
                    <a class="nav-link text-warning" href="{% url 'shows:allshows' %}">All shows</a>
                </li>
                <!-- <li>
                    <a class="nav-link text-warning" href="{% url 'shows:allshows' %}">Go Back</a>
                </li> -->
                <li>
                    <a class="nav-link text-warning" href="{% url 'shows:new_page' %}">Add a show</a>
                </li>
            </ul>
            <!-- Left links -->
      
            <!-- Search form -->
            <form class="d-flex input-group w-auto" action="{% url 'shows:search_show' %}" method="POST">
                {% csrf_token %}
                <input
                    type="search"
                    class="form-control"
                    placeholder="Search a show"
                    aria-label="Search"
                    name="searched"
                />
                <button
                    class="btn btn-outline-warning"
                    type="submit"
                    data-mdb-ripple-color="light"
                >
                    Search
                </button>
            </form>
          </div>
          <!-- Collapsible wrapper -->
        </div>
        <!-- Container wrapper -->
      </nav>
      <!-- Navbar -->
      <img src="https://images.wallpaperscraft.com/image/hollywood_word_inscription_178304_2560x1024.jpg" class="img-fluid" alt="..." />
      
<!-- MDB -->
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.3.0/mdb.min.js"
></script>
{% block content %}
{% endblock content %}

shows/templates/shows/new_page.html
{% extends 'shows/base.html' %}
{% load static %}
{% load crispy_forms_filters %} 
{% block content %}
    <h1 class="display-6">Add your new favorite show:</h1>
    <div class="w-50 shadow p-3 mb-5 bg-white rounded mx-auto" style="background-color:silver" >
        <form action="{% url 'shows:new_page' %}" method='post' enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="btn btn-success btn-sm ">Create</button>
        <a href="{% url 'shows:allshows' %}" type='button' class="btn btn-warning btn-sm mt-4 ml-3">Cancel</a>
        </form>
    </div>
{% endblock content %}

shows/templates/shows/search_show.html
{% extends 'shows/base.html' %}
{% load static %}
{% block content %}
    {% if searched %}
        <table class='table align-middle'>
            <thead>
                <tr>
                    <th scope="col" style='text-align: center'>Stage Photo</th>
                    <th scope="col" style='text-align: center'>Title</th>
                    <th scope="col" style='text-align: center'>Description</th>
                </tr>
            </thead>
            {% for show in searched_show %}
            <tbody>
                <tr>  
                    <td>
                        <img src="/media/{{ show.image }}" width="200px" height="150px" alt="{{ show.title }}">
                    </td>
                    <td class="description"><h6>{{ show.title }}</h6></td>
                    <td class="description">
                        <p>{{ show.description }}</p>
                    </td>
                </tr>
            </tbody>
            {% endfor %}
        </table>
    {% else %}
    <h3>Sorry... Make sure you searhed something...</h3>
    {% endif %}
    <!-- <nav aria-label="...">
        <ul class="pagination pagination justify-content-center">
            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">Top</a>
                            <a href="?page={{ page_obj.previous_page_number }}">
                                <i class="fas fa-hand-point-left"></i>
                            </a>
                    {% endif %}
                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                    </span>
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">
                            <i class="fas fa-hand-point-right"></i>
                        </a>
                        <a href="?page={{page_obj.paginator.num_pages }}">Bottom</a>
                    {% endif %}
                </span>
            </div>
        </ul>
    </nav> -->
{% endblock content %}

shows/templates/shows/show_detail.html
{% extends 'shows/base.html' %}
{% load static %}
{% block content %}

    <div class="card" style="width: 18rem">
        <img 
            src="/media/{{ this_show.image }}" width="auto" height="200px" 
            class="card-img-top"
            alt="the big bang theory">
        <div class="card-body">
            <h5 class="card-title">Introduction</h5>
            <p class='card-text'>
                {{ this_show.description }}
            </p>
        </div>
        <ul class="list-group list-group-flush">
            <li class='list-group-item'>Title: {{ this_show.title }}</li>
            <li class='list-group-item'>Network: {{ this_show.network }}</li>
            <li class='list-group-item'>Released: {{ this_show.released_date }}</li>
        </ul>
        <div class='card-body'>
            <a class="btn btn-secondary" href="{% url 'shows:edit_show' this_show.id %}">Edit</a>
            <a class="btn btn-danger" href="{% url 'shows:delete_show' this_show.id %}">Delete</a>
            <a class="btn btn-warning" href="{% url 'shows:allshows' %}">Back</a>
        </div>
    </div>
 
{% endblock content %}

shows/templates/shows/update_show.html
{% extends 'shows/base.html' %}
{% load static %}
{% load crispy_forms_filters %} 
{% block content %}
    <h2 class="display-6">Update TV Show {{ update_show.id }}</h2>
    <div class="w-50 shadow p-3 mb-5 bg-white rounded mx-auto" style="background-color:silver" >
        <form action="{% url 'shows:edit_show' update_show.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="btn btn-success btn-sm ">Update</button>
        <a href="{% url 'shows:allshows' %}" type='button' class="btn btn-warning btn-sm mt-4 ml-3">Cancel</a>
        </form>
    </div>
{% endblock content %}